### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by juliocezar96**

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-188683 Script</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-188683">Script</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Medium</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Closed</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>SE Support</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Nilton Vieira da Silva</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

7 files changed, 960 insertions(+), 31 deletions(-)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Pull request closed without merging**
